- easyReflectometryApp/Gui/Pages/Analysis/SideBarAdvanced.qml
- easyReflectometryApp/Gui/Pages/Sample/SideBarAdvanced.qml
- easyReflectometryApp/Logic/Proxies/Plotting1d.py
> Option to invert SLD plot in both the fitter and sample tabs

- EasyReflectometryApp/Gui/Pages/Sample/SideBarBasic.qml
- EasyReflectometryApp/Logic/Proxies/Calculator.py
- EasyReflectometryApp/Logic/Proxies/Fitter.py
- EasyReflectometryApp/Logic/Proxies/Material.py
- EasyReflectometryApp/Logic/Proxies/Model.py
- EasyReflectometryApp/Logic/Proxies/Parameter.py
- EasyReflectometryApp/Logic/Proxies/Simulation.py
- EasyReflectometryApp/Logic/Proxies/UndoRedo.py
- EasyReflectometryApp/Logic/PyQmlProxy.py
This brings the surfactant item type into the GUI. This is a first version and *has* bugs, but these will be resolved in time.
> First version of the surfactant GUI

- EasyReflectometryApp/Gui/Pages/Sample/SideBarBasic.qml
- EasyReflectometryApp/Logic/Proxies/Material.py
- EasyReflectometryApp/Logic/Proxies/Model.py
- EasyReflectometryApp/Logic/Proxies/Parameter.py
- EasyReflectometryApp/Logic/Proxies/Simulation.py
- EasyReflectometryApp/Logic/Proxies/UndoRedo.py
- EasyReflectometryApp/Logic/PyQmlProxy.py
Sorting some small bug fixes: 
- Using the pure reflectometry in the sample tab again (from https://github.com/easyScience/EasyReflectometryLib/pull/29)
- The text box for the number of reps is now big enough to show the full text
- An now out of data EasyCore import was updated
- The parameter code was improved (very slightly, this should be refactored more)
Additionally there was improvements to the efficiency of the GUI logic, so that now when changes are enacted in the item editor they do not effect the model editor.
> Small fixes and slight efficiency improvement

- EasyReflectometryApp/Logic/Proxies/Calculator.py
- EasyReflectometryApp/Logic/Proxies/Fitter.py
- EasyReflectometryApp/Logic/Proxies/Material.py
- EasyReflectometryApp/Logic/Proxies/Model.py
- EasyReflectometryApp/Logic/Proxies/Simulation.py
- EasyReflectometryApp/Logic/Proxies/State.py
- EasyReflectometryApp/Logic/PyQmlProxy.py
- pyproject.toml
Waiting on https://github.com/easyScience/EasyReflectometryLib/pull/37 before any merge can occur.
> Modifications to use a single interface for all models/data

- EasyReflectometryApp/Gui/Pages/Project/SideBarBasic.qml
> Enable toggle to sample view on continuing without a project

- EasyReflectometryApp/Gui/Logic/Plotting.js
- EasyReflectometryApp/Gui/Logic/PyQmlProxy.js
- EasyReflectometryApp/Gui/Pages/Analysis/SideBarAdvanced.qml
- EasyReflectometryApp/Gui/Pages/Experiment/SideBarAdvanced.qml
- EasyReflectometryApp/Gui/Pages/Sample/SideBarAdvanced.qml
- EasyReflectometryApp/Logic/Proxies/Plotting1d.py
> Add a toggle switch in the plot menu for logarithmic q-axes

- README.md
- ROADMAP.md
Also looking for input from @jfkcooper (in particular on the hard condensed matter part).
> Add a roadmap development plan

- .github/workflows/snapcraft.yml
- snap/gui/EasyReflectometry.desktop
- snap/gui/er_logo.svg
- snap/snapcraft.yaml
When this is merged to master, a snapcraft image will be created and pushed to the snap store under `EasyReflectometry`
> Building snapcraft images

- EasyReflectometryApp/Gui/Components/CloseDialog.qml
> Correct proxy path

- EasyReflectometryApp/Gui/Components/ResultsDialog.qml
- EasyReflectometryApp/Gui/Pages/Sample/MultiLayerTable.qml
- EasyReflectometryApp/Logic/DataStore.py
- EasyReflectometryApp/Logic/Proxies/Fitter.py
- pyproject.toml
This PR gets everything *working* with EasyCore-0.3.0 but does not take advantage of any new features except the MultiFitter.
> Easycore-0.3.0

- EasyReflectometryApp/Gui/Components/AnalysisFitables.qml
- EasyReflectometryApp/Gui/Components/ApplicationWindow.qml
- EasyReflectometryApp/Gui/Pages/Project/MainContentDescription.qml
- EasyReflectometryApp/Gui/Pages/Sample/MultiLayerTable.qml
- EasyReflectometryApp/Gui/Pages/Sample/SideBarAdvanced.qml
- EasyReflectometryApp/Gui/Pages/Sample/SideBarBasic.qml
- EasyReflectometryApp/Gui/Pages/Sample/SurfactantTable.qml
- EasyReflectometryApp/Logic/Proxies/Calculator.py
- EasyReflectometryApp/Logic/Proxies/Fitter.py
- EasyReflectometryApp/Logic/Proxies/Material.py
- EasyReflectometryApp/Logic/Proxies/Model.py
- EasyReflectometryApp/Logic/Proxies/Parameter.py
- EasyReflectometryApp/Logic/Proxies/Project.py
- EasyReflectometryApp/Logic/Proxies/Simulation.py
- EasyReflectometryApp/Logic/Proxies/State.py
- EasyReflectometryApp/Logic/PyQmlProxy.py
This branch contains some fixes for issues listed in the [ROADMAP](https://github.com/easyScience/EasyReflectometryApp/blob/main/ROADMAP.md)
Also, quite some effort was made to speed up certain GUI operations.
Addresses:
https://github.com/easyScience/EasyReflectometryApp/issues/102
https://github.com/easyScience/EasyReflectometryApp/issues/124
+ some other issues noticed
> Performance and other fixes

- .github/workflows/linux-build.yml
- .github/workflows/macos-windows-build.yml
- CHANGELOG.md
- INSTALLATION.md
- README.md
- pyproject.toml
- tools/Scripts/MakeInstaller.py
No changes to code.  Just a check of the release protocol.
Updated `QtInstallerFramework`
Removed `OnlineRepository`
- When installing the app with the new framework it polls for an update and hangs
Updated dependencies
> Update version number to check release protocol

- .github/workflows/macos-windows-build.yml
- EasyReflectometryApp/Gui/Components/UserTutorialsController.qml
- pyproject.toml
- tools/Scripts/RunApp.py
Added 30 s wait when running in testmode to make it possible to ensure that Qt was started up
Please ensure that the created OSX artifact is functional.  From the pipeline it seems to be the case.
> 177 fix to make osx runable

- EasyReflectometryApp/Logic/Proxies/Material.py
- EasyReflectometryApp/Logic/Proxies/Model.py
- EasyReflectometryApp/Logic/Proxies/Parameter.py
- EasyReflectometryApp/Logic/Proxies/Project.py
- EasyReflectometryApp/Logic/Proxies/Simulation.py
- EasyReflectometryApp/Logic/PyQmlProxy.py
- pyproject.toml
Only renaming caused be changes in the Lib.
By far the most changes are made in `Model.py`
> Adjustments for the App to work with Lib v.0.0.6

- .github/workflows/macos-windows-build.yml
- EasyReflectometryApp/Gui/Pages/Sample/SurfactantTable.qml
- EasyReflectometryApp/Logic/Proxies/Model.py
Added section to Testing in Hand for ERA: https://github.com/EasyScience/EasyReflectometryApp/wiki/Testing-in-Hand
Fix to make surfactant table appear correctly in GUI.
Now: 
Before:
`area per molecule` and `solvation` should be changed from `floats` to EasyScience `parameters` to enable the expected behaviour of the GUI
https://github.com/EasyScience/EasyReflectometryLib/issues/171
https://github.com/EasyScience/EasyReflectometryApp/issues/193
> 192 surfactant layer table

- .github/workflows/macos-windows-build.yml
- EasyReflectometryApp/Gui/Pages/Sample/SurfactantTable.qml
- EasyReflectometryApp/Logic/Proxies/Model.py
> 192 surfactant layer table (#194)

- EasyReflectometryApp/Logic/DataStore.py
- EasyReflectometryApp/Logic/Proxies/Data.py
- EasyReflectometryApp/Logic/Proxies/Material.py
- EasyReflectometryApp/Logic/Proxies/Model.py
- EasyReflectometryApp/Logic/Proxies/Project.py
- pyproject.toml
Use functionality that have been moved to Lib
> 208 move functionality from proxy sample into the lib

- EasyReflectometryApp/Logic/Proxies/Project.py
- EasyReflectometryApp/Logic/Proxies/Simulation.py
- pyproject.toml
Using the functionality in the Lib
> Project functionality is moved into Lib

- EasyReflectometryApp/Logic/Proxies/Project.py
Minor adjustments to fit the latest version of the project class
> Adjustments to fit latest version of Project class in lib

- EasyReflectometryApp/Gui/Pages/Project/ProjectDescriptionDialog.qml
- src_qt6/EasyReflectometryApp/Backends/Mock/Project.qml
- src_qt6/EasyReflectometryApp/Backends/Py/logic/project.py
- src_qt6/EasyReflectometryApp/Backends/Py/logic/status.py
- src_qt6/EasyReflectometryApp/Backends/Py/project.py
- src_qt6/EasyReflectometryApp/Backends/Py/py_backend.py
- src_qt6/EasyReflectometryApp/Backends/Py/report.py
- src_qt6/EasyReflectometryApp/Backends/Py/status.py
- src_qt6/EasyReflectometryApp/Gui/ApplicationWindow.qml
- src_qt6/EasyReflectometryApp/Gui/Globals/BackendWrapper.qml
- src_qt6/EasyReflectometryApp/Gui/Pages/Project/Sidebar/Basic/Popups/OpenJsonFile.qml
- src_qt6/EasyReflectometryApp/Gui/Pages/Project/Sidebar/Basic/Popups/ProjectDescription.qml
- src_qt6/pyproject.toml
In Qt6 implementation use the new project class from lib
> Project in qt6
